### ISSUE TITLE
 .format("com.microsoft.sqlserver.jdbc.spark") does not work on Azure Databricks Spark 3.2+

### ISSUE THREAD

**Issue by Git-BT-Hub** [microsoft/sql-spark-connector#233]
Hi All,
Below does not work on Azure Databricks Spark 3.2+ (DBR 12.1 LTS and above)

  df.write \     .format("com.microsoft.sqlserver.jdbc.spark") \

Error: Py4JJavaError: An error occurred while calling o934.save.
: java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.getSchema(Ljava/sql/ResultSet;Lorg/apache/spark/sql/jdbc/JdbcDialect;Z)Lorg/apache/spark/sql/types/StructType;

Thanks
