### ISSUE TITLE
Spark 3.1 support

### ISSUE THREAD

**Issue by pmooij** [microsoft/sql-spark-connector#97]
Databricks [has introduced the 8 series runtimes](https://docs.databricks.com/release-notes/runtime/releases.html#supported-databricks-runtime-releases-and-support-schedule) which are build uppon **Spark 3.1.1**, as shown in the image below.
The `com.microsoft.azure:spark-mssql-connector_2.12_3.0:1.0.0-alpha` is perfectly working on Spark 3.0.x but unfortunately not working on Spark 3.1.x. 

If possible it would be great if the Spark 3 connector could work with all **Spark 3.x.x**
If required updates for Spark 3.1 are not backward compatible with Spark 3.0 it would be great if a **Spark 3.1.x** compatible connector could be introduced

I would be happy to help but in this case I have no clue where to start.

### error logs on Databricks Runtime 8.1 ML
```java
Py4JJavaError: An error occurred while calling o483.save.
: java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.schemaString(Lorg/apache/spark/sql/Dataset;Ljava/lang/String;Lscala/Option;)Ljava/lang/String;
	at com.microsoft.sqlserver.jdbc.spark.BulkCopyUtils$.mssqlCreateTable(BulkCopyUtils.scala:506)
	at com.microsoft.sqlserver.jdbc.spark.SingleInstanceConnector$.createTable(SingleInstanceConnector.scala:46)
	at com.microsoft.sqlserver.jdbc.spark.Connector.write(Connector.scala:73)
	at com.microsoft.sqlserver.jdbc.spark.DefaultSource.createRelation(DefaultSource.scala:64)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:73)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:71)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:94)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:196)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:240)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:165)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:236)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:192)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:163)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:162)
	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:1079)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$5(SQLExecution.scala:126)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:267)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:104)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:843)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:77)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:217)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:1079)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:468)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:438)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:311)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
```

### [supported-databricks-runtime-releases-and-support-schedule](https://docs.databricks.com/release-notes/runtime/releases.html#supported-databricks-runtime-releases-and-support-schedule)
![image](https://user-images.githubusercontent.com/12949389/112342504-8eaa4680-8cc2-11eb-9efe-998771685b81.png)

**Comment by crashdomi** [comment]
Would be highly appreciated!

**Comment by dsuarez993** [comment]
Any progress on this?

**Comment by zegor** [comment]
Yes please! As time goes on, this compatibility becomes more important.

**Comment by RKNUTALAPATI** [comment]
This change is must required, As we are not able to use this lib on DataBricks 8.X runtime version.

**Comment by KrishnaSQL** [comment]
waiting for the new release of this connector to work with the new DataBricks runtime version at least  8.4 onwards.

**Comment by BrendBraeckmans** [comment]
Hi all,

Is there a way to make a build locally based on [PR-134](https://github.com/microsoft/sql-spark-connector/pull/134) that would be able to run on Databricks runtime 8 versions ? 

A bit the same as could be done before when spark 3.0 versions were not supported yet  and is described [here](https://github.com/microsoft/sql-spark-connector/issues/15) .

**Comment by ruiyang2015** [comment]
+1, even an alpha release is very helpful, at least unblock us from using it in spark 3.1.2

**Comment by dsu4rez** [comment]
@shivsood Thanks a lot for this new version! Has it been published to Maven already?

**Comment by KrishnaSQL** [comment]
Thanks for the fix.
I couldn't the new version in Maven as of now, can you advise the timelines on the new release as we have hold the Databricks runtime version upgrade to 8.x ?
