### PR TITLE
Upgrade to Spark 3.3.0

### LINKED ISSUE #191: Support for Spark 3.3
Hi, when I try to use the connector with Spark 3.3 my Spark jobs crash with the following stack trace:

```
Caused by: java.lang.NoSuchMethodError: 'scala.Function0 org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.createConnectionFactory(org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions)'
	at com.microsoft.sqlserver.jdbc.spark.DefaultSource.createRelation(DefaultSource.scala:56)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:84)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:109)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:169)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:95)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:94)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:584)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:176)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:584)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:560)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:94)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:81)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:79)
	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:116)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:860)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:390)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:363)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:247)
        ...
```

I know that there's no official support for Spark 3.2 (see also #164), but so far it has worked for me anyways. However, after upgrading to 3.3, the exception above appears.

I am using Databricks and want to upgrade to [Databricks runtime version 11.0](https://docs.databricks.com/release-notes/runtime/11.0.html), which uses Spark 3.3 now. However, this connector is the only dependency that still prevents us from upgrading.

### PR DESCRIPTION
**Pull request by moredatapls**
- Bump Spark to 3.3.0: replaced the usage of the removed `JdbcUtils.getConnectionFactory` with an own implementation
- Add integration tests to
  - create a JDBC connection using the new utils
  - write data to and read data from a SQL server
- Added a docker compose setup to spin up a local instance of SQL server
- Bumped the version of the library to 1.3.0
- Updated the readme accordingly
  - Added the 1.3.0 artifact to the version table
  - Added instructions on how to run the tests

Fixes #191

### CODE REVIEW

**Review by SteffenMangold — APPROVED** [review]
Very nice! New tests are a good code evolution.

**Comment by moredatapls** [comment]
If anyone finds this PR and wants support for Spark 3.3.0: head over to https://github.com/solytic/sql-spark-connector/releases/tag/v1.4.0 and use the build that we created at Solytic, since Microsoft seems to not be so active here

**Comment by arihar268** [comment]
Even after the fix facing the below issue with Spark version 3.3 and scala version 2.12.15. Included the dependent libraries in build.sbt running on databricks runtime cluster 11.3 LTS

 java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.getSchema(Ljava/sql/ResultSet;Lorg/apache/spark/sql/jdbc/JdbcDialect;Z)Lorg/apache/spark/sql/types/StructType;
	at com.microsoft.sqlserver.jdbc.spark.BulkCopyUtils$.matchSchemas(BulkCopyUtils.scala:306)
	at com.microsoft.sqlserver.jdbc.spark.BulkCopyUtils$.getColMetaData(BulkCopyUtils.scala:267)
	at com.microsoft.sqlserver.jdbc.spark.Connector.write(Connector.scala:79)

Provided in build.sbt

name := "spark-mssql-connector"

organization := "com.microsoft.sqlserver.jdbc.spark"

version := "1.0.0"

scalaVersion := "2.12.15"

val sparkVersion = "3.3.0" 

javacOptions ++= Seq("-source", "1.8", "-target", "1.8", "-Xlint")

initialize := {
  val _ = initialize.value
  val javaVersion = sys.props("java.specification.version")
  if (javaVersion != "1.8")
    sys.error("Java 1.8 is required for this project. Found " + javaVersion + " instead")
}

scalacOptions := Seq("-deprecation", "-unchecked", "-Dscalac.patmat.analysisBudget=1024", "-Xfuture")

libraryDependencies ++= Seq(
  "com.microsoft.sqlserver" % "mssql-jdbc" % "8.4.1.jre8",
  "org.apache.spark" %% "spark-parent" % "3.3.0" % "provided",
  "org.scala-lang.modules" %% "scala-parser-combinators" % "1.1.2",
  "org.apache.spark" %% "spark-sql" % sparkVersion % "provided",
  "org.apache.spark" %% "spark-yarn" % sparkVersion,
  "org.scala-lang" % "scala-library" % "2.12.11" % "test",
  "org.apache.spark" %% "spark-core" % sparkVersion % "provided",
  "org.apache.spark" %% "spark-catalyst" % sparkVersion % "provided",
  "org.scalactic" %% "scalactic" % "3.2.6" % "test",
  "org.scalatest" %% "scalatest" % "3.2.6" % "test",
  "com.novocode" % "junit-interface" % "0.11"
  )

scalacOptions := Seq("-unchecked", "-deprecation", "evicted")

assemblyJarName in assembly := s"${name.value}_${scalaBinaryVersion.value}-${sparkVersion}_${version.value}.jar"

// Exclude scala-library from this fat jar. The scala library is already there in spark package.
assemblyOption in assembly := (assemblyOption in assembly).value.copy(includeScala = false)

assemblyMergeStrategy in assembly := {
 case PathList("META-INF",xs @ _*) => MergeStrategy.discard
 case _                        => MergeStrategy.first
}

Am I missing anythings?

**Comment by moredatapls** [comment]
@arihar268 the project only contains a [pom.xml](https://github.com/microsoft/sql-spark-connector/blob/master/pom.xml), not a build.sbt. Where did you find this file?

File: src/main/scala/com/microsoft/sqlserver/jdbc/spark/utils/JdbcUtils.scala [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+
+object JdbcUtils {
+  /**
+   * Creates a JDBC connection using the input JDBC options.
+   * @param options The options which are used to create the connection.
+   * @return A JDBC connection.
+   */
+  def createConnection(options: JDBCOptions): Connection = {
+    val dialect = JdbcDialects.get(options.url)
+    val conn = dialect.createConnectionFactory(options)(-1)
```
Comment (shivsood) [inline src/main/scala/com/microsoft/sqlserver/jdbc/spark/utils/JdbcUtils.scala:16]: Has this changed in Spark 3.3. Earlier we were using createConnectionFactory directly without dialect.createConnectionFactory.

File: src/test/scala/com/microsoft/sqlserver/jdbc/spark/integration/SqlServerReadWriteTests.scala [hunk 2]
```diff
@@ -0,0 +1,81 @@
+package com.microsoft.sqlserver.jdbc.spark.integration
```
Comment (shivsood) [inline src/test/scala/com/microsoft/sqlserver/jdbc/spark/integration/SqlServerReadWriteTests.scala:1]: Tests are great additions. Would be good to have all regression test added as part of this framework. 
Should be a separate PR though, and this be kept at JDBC compact change.

**Comment by shivsood** [comment]
@moredatapls thansk for PR. Please consider splitting these as 2 PRs. 
1 for jdbc connection change, 
2. for adding the sparkfun based test framework./docker change to spin up the sql server.

Also did u run the regression test on spark 3.3.0 with this. If so, could you please add the test results here. Thanks again for work

@luxu-ms as FYI.

**Review by shivsood — CHANGES_REQUESTED** [review]
@moredatapls thansk for PR. This looks good to me, overall. 

Requesting some small changes. 
Please consider splitting these as 2 PRs. 
1 for jdbc connection change, 
2. for adding the sparkfun based test framework./docker change to spin up the sql server.

Also did u run the regression test on spark 3.3.0 with this? If so, could you please add the test results here. Thanks again for work. 

@luxu-ms

**Comment by arihar268** [comment]
@moredatapls , I am using the same code which is in the PR. But I don't want any test files so I have removed those and created a build.sbt to create a jar.

**Comment by tfabritz** [comment]
I can see the same error that @arihar268 is seeing when using the build provided over at Solytic: 
`java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.getSchema(Ljava/sql/ResultSet;Lorg/apache/spark/sql/jdbc/JdbcDialect;Z)Lorg/apache/spark/sql/types/StructType;`

It only is happening when using truncate as write mode.

File: pom.xml [hunk 3]
```diff
@@ -208,7 +208,7 @@
             <properties>
                 <scala.binary.version>2.12</scala.binary.version>
                 <scala.version>2.12.11</scala.version>
-                <spark.version>3.1.2</spark.version>
+                <spark.version>3.3.0</spark.version>
```
Comment (luxu1-ms) [inline pom.xml:211]: Could you remove the spark24 and spark31 profiles in pom file?

**Review by luxu1-ms — CHANGES_REQUESTED** [review]

**Comment by dimtsi** [comment]
Is there any  update on this? It is also a blocker for me and my colleagues to move to DBR 11.3

**Comment by syedhassaanahmed** [comment]
Its been 7 months since Spark 3.3 was released. @shivsood @luxu1-ms Any update on getting this PR merged?

**Comment by julupanter** [comment]
Please! This is mandatory for DBR 11.3 and unity catalog!
Thank you for your work!

File: pom.xml (hunk 3 above)
Comment (moredatapls) [reply pom.xml:211]: as in update the name of the profile, or add a new one? i renamed the profile, let me know if I should add a second one for Spark 3.3.0

File: src/test/scala/com/microsoft/sqlserver/jdbc/spark/integration/SqlServerReadWriteTests.scala (hunk 2 above)
Comment (moredatapls) [reply src/test/scala/com/microsoft/sqlserver/jdbc/spark/integration/SqlServerReadWriteTests.scala]: removed, will publish another PR later with the integration tests

**Comment by moredatapls** [comment]
@luxu1-ms @shivsood please check again

File: src/main/scala/com/microsoft/sqlserver/jdbc/spark/utils/JdbcUtils.scala [hunk 4]
```diff
@@ -0,0 +1,19 @@
...
+    conn
+  }
+}
```
Comment (luxu1-ms) [inline src/main/scala/com/microsoft/sqlserver/jdbc/spark/utils/JdbcUtils.scala:19]: I would recommend only modify the createConnectionFactory instead of adding a new JdbcUtils.scala, as there is only one method, and we could use two lines or even one line. Something like below,
val dialect = JdbcDialects.get(options.url)
val conn = dialect.createConnectionFactory(options)(-1)

**Comment by luxu1-ms** [comment]
> @luxu1-ms @shivsood please check again

**Comment by luxu1-ms** [comment]
> > @luxu1-ms @shivsood please check again

@

File: src/main/scala/com/microsoft/sqlserver/jdbc/spark/utils/JdbcUtils.scala (hunk 4 above)
Comment (moredatapls) [reply src/main/scala/com/microsoft/sqlserver/jdbc/spark/utils/JdbcUtils.scala:19]: I was trying to be DRY, but if you prefer it I can change it. My thought was that a central place to create the connection would also help us in the future to apply changes. And I think the `JbdbUtils` name makes sense because in Spark they use the same: https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/JdbcUtils.scala

Comment (moredatapls) [reply src/main/scala/com/microsoft/sqlserver/jdbc/spark/utils/JdbcUtils.scala:19]: Any thoughts on this @shivsood ?

Comment (luxu1-ms) [reply src/main/scala/com/microsoft/sqlserver/jdbc/spark/utils/JdbcUtils.scala:19]: Spark JdbcUtils.scala defines methods such as truncateTable, getSchema,  savePartition, similiar to [BulkCopyUtils.scala](https://github.com/microsoft/sql-spark-connector/blob/master/src/main/scala/com/microsoft/sqlserver/jdbc/spark/utils/BulkCopyUtils.scala) for Spark MsSQL Connector.
We could have a method for creating connection, but have a new file only for this connection is way too much. I could not think of any other methods in connector jdbcUtils.scala except we change the entire structure.

**Review by shivsood — APPROVED** [review]
Looks good to me now. Please ensure test runs and attach results to PR. We ran this fix on DBR 11.3 and there is any exception. Turns out that a DBR issue that they need to fix. @luxu1-ms

**Comment by moredatapls** [comment]
>  Please ensure test runs and attach results to PR

@shivsood what do you mean by this? doesn't one of you need to trigger the tests in CI? I can't do it

image

**Comment by shivsood** [comment]
Merging. Test pass by @luxu1-ms

**Comment by hmayer1980** [comment]
And when do we expect to see a final Version on Maven?
https://mvnrepository.com/artifact/com.microsoft.azure/spark-mssql-connector_2.12

Currently I see only a 1.3.0-BETA Version?

**Comment by smialkow** [comment]
Is there any update on the final release of 1.3? I am not even considering using a beta version for production.
