### ISSUE TITLE
NoClassDefFoundError: org/apache/spark/sql/execution/datasources/jdbc/JdbcOptionsInWrite

### ISSUE THREAD

**Issue by SUDIPSJE** [microsoft/sql-spark-connector#75]
```
Dataset<Row> driverNodesDataset = 
                         spark.read()
                           .format("com.microsoft.sqlserver.jdbc.spark")
                           .option("url", url).option("dbtable", table_name)
                           .option("user", username)
                           .option("password", password)
                           .load();
```
I am getting an error **`Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/sql/execution/datasources/jdbc/JdbcOptionsInWrite`** while executing the above code.

My Spark Cluster Version is 2.3.0. Does this work with Spark 2.3?

Thanks.

**Comment by arvindshmicrosoft** [comment]
Yes, this functionality was added as part of [SPARK-24423](https://issues.apache.org/jira/browse/SPARK-24423), which was released with Spark 2.4.0.
