### ISSUE TITLE
Support for Spark 3.3

### ISSUE THREAD

**Issue by moredatapls** [microsoft/sql-spark-connector#191]
Hi, when I try to use the connector with Spark 3.3 my Spark jobs crash with the following stack trace:

```
Caused by: java.lang.NoSuchMethodError: 'scala.Function0 org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.createConnectionFactory(org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions)'
	at com.microsoft.sqlserver.jdbc.spark.DefaultSource.createRelation(DefaultSource.scala:56)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:84)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:109)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:169)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:95)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:94)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:584)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:176)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:584)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:560)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:94)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:81)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:79)
	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:116)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:860)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:390)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:363)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:247)
        ...
```

I know that there's no official support for Spark 3.2 (see also #164), but so far it has worked for me anyways. However, after upgrading to 3.3, the exception above appears.

I am using Databricks and want to upgrade to [Databricks runtime version 11.0](https://docs.databricks.com/release-notes/runtime/11.0.html), which uses Spark 3.3 now. However, this connector is the only dependency that still prevents us from upgrading.

**Comment by qwead520** [comment]
Azure Synapse supports spark 3.2 runtime, but connectors are not ready. 
So embarrassed.

**Comment by moredatapls** [comment]
Not sure who are the maintainers here, but I created a PR #197 that should fix this issue

**Comment by moredatapls** [comment]
If anyone is interested: we at Solytic created a fork of the repository because it seems like Microsoft is not very active here and we really needed Spark 3.3 support. If you want you can check out the release over here: https://github.com/solytic/sql-spark-connector/releases/tag/v1.4.0

**Comment by ibelieveai** [comment]
> If anyone is interested: we at Solytic created a fork of the repository because it seems like Microsoft is not very active here and we really needed Spark 3.3 support. If you want you can check out the release over here: https://github.com/solytic/sql-spark-connector/releases/tag/v1.4.0

thank you @moredatapls

**Comment by dalmat36** [comment]
@luxu1-ms any thoughts on timeline for Spark 3.3 compatible version? Thanks!

**Comment by mooreprabu** [comment]
We also ran into the same issue with Databricks runtime 11.3, which runs on spark 3.3.0.

Error message: 
"java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.createConnectionFactory(Lorg/apache/spark/sql/execution/datasources/jdbc/JDBCOptions;)Lscala/Function0;"

**Comment by sl2bigdata** [comment]
Please prioritize this if possible. It is blocking many people from moving Databricks to 11.3 lts runtime.  Thanks

**Comment by shivsood** [comment]
Yes, this is being addressed. @luxu1-ms

**Comment by vijaygopal2005** [comment]
Any updates on this issue ? We are also facing the same issue and blocking our upgrade from 7.3  to 11.3 runtime on Databricks.

**Comment by amrutalonkar123** [comment]
I was also facing the same issue.
Tried this code to write a table to sql server db it worked for me. 
  df=df.write \
              .format("jdbc") \
              .option("url", url[env.lower()]) \
              .option("dbtable", f"{tableName}") \
              .option("accessToken", access_token) \
              .option("encrypt", "true") \
              .option("hostNameInCertificate", "*.database.windows.net") \
              .option("truncate","true") \
              .mode("overwrite") \
              .save()
  return df

**Comment by sl2bigdata** [comment]
> I was also facing the same issue. library for sql connector- com.microsoft.azure:spark-mssql-connector_2.12:1.2.0 Databricks runtime version- 11.3 LTS (includes Apache Spark 3.3.0, Scala 2.12) Tried this code to write a table to sql server db it worked for me. df=df.write .format("jdbc") .option("url", url[env.lower()]) .option("dbtable", f"{tableName}") .option("accessToken", access_token) .option("encrypt", "true") .option("hostNameInCertificate", "*.database.windows.net") .option("truncate","true") .mode("overwrite") .save() return df
> 
> Let me know if it solved your issue

You're not using the spark sql connector but native JDBC..

Try this:

.format("com.microsoft.sqlserver.jdbc.spark")\
    .mode(mode)\
    .option("truncate", True)\
    .option("url", url)\
    .option("dbtable", dbTable)\
    .option("user", user)\
    .option("password", password)\
    .option("driver","com.microsoft.sqlserver.jdbc.SQLServerDriver")\
    .option("batchsize", batchSize)\
    .option("schemaCheckEnabled",False)\
    .save()

**Comment by amrutalonkar123** [comment]
I tried your solution @sl2bigdata but it gave me the same error

**Comment by Git-BT-Hub** [comment]
Hi,
I was getting same Error

Thanks @amrutalonkar123 , tried your solution it works 

**I am able to BulkInsert 1million+ rows under 30 secs

###THIS Works
df_sum.write \
        .format("jdbc") \
        .option("url", db_sql_url) \
        .option("dbtable", db_table_name) \
        .option("databaseName", jdbcDatabase) \
        .option("accessToken", token) \
        .option("encrypt", "true") \
        .option("hostNameInCertificate", "*.database.windows.net") \
        .mode("append") \
        .save()

###THIS DOES-NOT-Work
df_sum.write \
        .format("com.microsoft.sqlserver.jdbc.spark") \
        .option("url", db_sql_url) \
        .option("dbtable", db_table_name) \
        .option("databaseName", jdbcDatabase) \
        .option("accessToken", token) \
        .option("encrypt", "true") \
        .option("hostNameInCertificate", "*.database.windows.net") \
        .mode("append") \
        .save()

Anyone finds a different solution, please tag me
Thanks

**Comment by dbeavon** [comment]
@Git-BT-Hub 
It is very unlikely that the JDBC is using an actual bulk insert operation via TDS wire protocol.

... What is more likely is that you are using a large batchsize (spark option) of 1000 rows by default to send data to SQL in a batched fashion.  On the receiving side the inserts themselves are probably still happening **one at a time.**  

You can use xevents to see what is happening.  I use azure data studio with the so-called "sql profiler" extension.
